```
uvx harlequin data/Chinook_Sqlite.sqlite 
```

In [1]:
import sqlite3
import pandas as pd

In [2]:
db_path = "../data/Chinook_Sqlite.sqlite"
db = sqlite3.connect(db_path)
cursor = db.cursor()

In [3]:
_q = """SELECT 1"""

cursor.execute(_q)
cursor.fetchall()

[(1,)]

In [4]:
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()
print(tables)

[('Album',), ('Artist',), ('Customer',), ('Employee',), ('Genre',), ('Invoice',), ('InvoiceLine',), ('MediaType',), ('Playlist',), ('PlaylistTrack',), ('Track',)]

In [5]:
_q = """SELECT * FROM Invoice"""

cursor.execute(_q)
cursor.fetchall()

[(1,
  2,
  '2021-01-01 00:00:00',
  'Theodor-Heuss-Straße 34',
  'Stuttgart',
  None,
  'Germany',
  '70174',
  1.98),
 (2,
  4,
  '2021-01-02 00:00:00',
  'Ullevålsveien 14',
  'Oslo',
  None,
  'Norway',
  '0171',
  3.96),
 (3,
  8,
  '2021-01-03 00:00:00',
  'Grétrystraat 63',
  'Brussels',
  None,
  'Belgium',
  '1000',
  5.94),
 (4,
  14,
  '2021-01-06 00:00:00',
  '8210 111 ST NW',
  'Edmonton',
  'AB',
  'Canada',
  'T6G 2C7',
  8.91),
 (5,
  23,
  '2021-01-11 00:00:00',
  '69 Salem Street',
  'Boston',
  'MA',
  'USA',
  '2113',
  13.86),
 (6,
  37,
  '2021-01-19 00:00:00',
  'Berger Straße 10',
  'Frankfurt',
  None,
  'Germany',
  '60316',
  0.99),
 (7,
  38,
  '2021-02-01 00:00:00',
  'Barbarossastraße 19',
  'Berlin',
  None,
  'Germany',
  '10779',
  1.98),
 (8,
  40,
  '2021-02-01 00:00:00',
  '8, Rue Hanovre',
  'Paris',
  None,
  'France',
  '75002',
  1.98),
 (9,
  42,
  '2021-02-02 00:00:00',
  '9, Place Louis Barthou',
  'Bordeaux',
  None,
  'France',
  '33000',
  3.96),
 (10,
  46,
  '2021-02-03 00:00:00',
  '3 Chatham Street',
  'Dublin',
  'Dublin',
  'Ireland',
  None,
  5.94),
 (11,
  52,
  '2021-02-06 00:00:00',
  '202 Hoxton Street',
  'London',
  None,
  'United Kingdom',
  'N1 5LH',
  8.91),
 (12,
  2,
  '2021-02-11 00:00:00',
  'Theodor-Heuss-Straße 34',
  'Stuttgart',
  None,
  'Germany',
  '70174',
  13.86),
 (13,
  16,
  '2021-02-19 00:00:00',
  '1600 Amphitheatre Parkway',
  'Mountain View',
  'CA',
  'USA',
  '94043-1351',
  0.99),
 (14,
  17,
  '2021-03-04 00:00:00',
  '1 Microsoft Way',
  'Redmond',
  'WA',
  'USA',
  '98052-8300',
  1.98),
 (15,
  19,
  '2021-03-04 00:00:00',
  '1 Infinite Loop',
  'Cupertino',
  'CA',
  'USA',
  '95014',
  1.98),
 (16,
  21,
  '2021-03-05 00:00:00',
  '801 W 4th Street',
  'Reno',
  'NV',
  'USA',
  '89503',
  3.96),
 (17,
  25,
  '2021-03-06 00:00:00',
  '319 N. Frances Street',
  'Madison',
  'WI',
  'USA',
  '53703',
  5.94),
 (18,
  31,
  '2021-03-09 00:00:00',
  '194A Chain Lake Drive',
  'Halifax',
  'NS',
  'Canada',
  'B3S 1C5',
  8.91),
 (19,
  40,
  '2021-03-14 00:00:00',
  '8, Rue Hanovre',
  'Paris',
  None,
  'France',
  '75002',
  13.86),
 (20,
  54,
  '2021-03-22 00:00:00',
  '110 Raeburn Pl',
  'Edinburgh ',
  None,
  'United Kingdom',
  'EH4 1HH',
  0.99),
 (21,
  55,
  '2021-04-04 00:00:00',
  '421 Bourke Street',
  'Sidney',
  'NSW',
  'Australia',
  '2010',
  1.98),
 (22,
  57,
  '2021-04-04 00:00:00',
  'Calle Lira, 198',
  'Santiago',
  None,
  'Chile',
  None,
  1.98),
 (23,
  59,
  '2021-04-05 00:00:00',
  '3,Raj Bhavan Road',
  'Bangalore',
  None,
  'India',
  '560001',
  3.96),
 (24,
  4,
  '2021-04-06 00:00:00',
  'Ullevålsveien 14',
  'Oslo',
  None,
  'Norway',
  '0171',
  5.94),
 (25,
  10,
  '2021-04-09 00:00:00',
  'Rua Dr. Falcão Filho, 155',
  'São Paulo',
  'SP',
  'Brazil',
  '01007-010',
  8.91),
 (26,
  19,
  '2021-04-14 00:00:00',
  '1 Infinite Loop',
  'Cupertino',
  'CA',
  'USA',
  '95014',
  13.86),
 (27,
  33,
  '2021-04-22 00:00:00',
  '5112 48 Street',
  'Yellowknife',
  'NT',
  'Canada',
  'X1A 1N6',
  0.99),
 (28,
  34,
  '2021-05-05 00:00:00',
  'Rua da Assunção 53',
  'Lisbon',
  None,
  'Portugal',
  None,
  1.98),
 (29,
  36,
  '2021-05-05 00:00:00',
  'Tauentzienstraße 8',
  'Berlin',
  None,
  'Germany',
  '10789',
  1.98),
 (30,
  38,
  '2021-05-06 00:00:00',
  'Barbarossastraße 19',
  'Berlin',
  None,
  'Germany',
  '10779',
  3.96),
 (31,
  42,
  '2021-05-07 00:00:00',
  '9, Place Louis Barthou',
  'Bordeaux',
  None,
  'France',
  '33000',
  5.94),
 (32,
  48,
  '2021-05-10 00:00:00',
  'Lijnbaansgracht 120bg',
  'Amsterdam',
  'VV',
  'Netherlands',
  '1016',
  8.91),
 (33,
  57,
  '2021-05-15 00:00:00',
  'Calle Lira, 198',
  'Santiago',
  None,
  'Chile',
  None,
  13.86),
 (34,
  12,
  '2021-05-23 00:00:00',
  'Praça Pio X, 119',
  'Rio de Janeiro',
  'RJ',
  'Brazil',
  '20040-020',
  0.99),
 (35,
  13,
  '2021-06-05 00:00:00',
  'Qe 7 Bloco G',
  'Brasília',
  'DF',
  'Brazil',
  '71020-677',
  1.98),
 (36,
  15,
  '2021-06-05 00:00:00',
  '700 W Pender Street',
  'Vancouver',
  'BC',
  'Canada',
  'V6C 1G8',
  1.98),
 (37,
  17,
  '2021-06-06 00:00:00',
  '1 Microsoft Way',
  'Redmond',
  'WA',
  'USA',
  '98052-8300',
  3.96),
 (38,
  21,
  '2021-06-07 00:00:00',
  '801 W 4th Street',
  'Reno',
  'NV',
  'USA',
  '89503',
  5.94),
 (39,
  27,
  '2021-06-10 00:00:00',
  '1033 N Park Ave',
  'Tucson',
  'AZ',
  'USA',
  '85719',
  8.91),
 (40,
  36,
  '2021-06-15 00:00:00',
  'Tauentzienstraße 8',
  'Berlin',
  None,
  'Germany',
  '10789',
  13.86),
 (41,
  50,
  '2021-06-23 00:00:00',
  'C/ San Bernardo 85',
  'Madrid',
  None,
  'Spain',
  '28015',
  0.99),
 (42,
  51,
  '2021-07-06 00:00:00',
  'Celsiusg. 9',
  'Stockholm',
  None,
  'Sweden',
  '11230',
  1.98),
 (43,
  53,
  '2021-07-06 00:00:00',
  '113 Lupus St',
  'London',
  None,
  'United Kingdom',
  'SW1V 3EN',
  1.98),
 (44,
  55,
  '2021-07-07 00:00:00',
  '421 Bourke Street',
  'Sidney',
  'NSW',
  'Australia',
  '2010',
  3.96),
 (45,
  59,
  '2021-07-08 00:00:00',
  '3,Raj Bhavan Road',
  'Bangalore',
  None,
  'India',
  '560001',
  5.94),
 (46,
  6,
  '2021-07-11 00:00:00',
  'Rilská 3174/6',
  'Prague',
  None,
  'Czech Republic',
  '14300',
  8.91),
 (47,
  15,
  '2021-07-16 00:00:00',
  '700 W Pender Street',
  'Vancouver',
  'BC',
  'Canada',
  'V6C 1G8',
  13.86),
 (48,
  29,
  '2021-07-24 00:00:00',
  '796 Dundas Street West',
  'Toronto',
  'ON',
  'Canada',
  'M6J 1V1',
  0.99),
 (49,
  30,
  '2021-08-06 00:00:00',
  '230 Elgin Street',
  'Ottawa',
  'ON',
  'Canada',
  'K2P 1L7',
  1.98),
 (50,
  32,
  '2021-08-06 00:00:00',
  '696 Osborne Street',
  'Winnipeg',
  'MB',
  'Canada',
  'R3L 2B9',
  1.98),
 (51,
  34,
  '2021-08-07 00:00:00',
  'Rua da Assunção 53',
  'Lisbon',
  None,
  'Portugal',
  None,
  3.96),
 (52,
  38,
  '2021-08-08 00:00:00',
  'Barbarossastraße 19',
  'Berlin',
  None,
  'Germany',
  '10779',
  5.94),
 (53,
  44,
  '2021-08-11 00:00:00',
  'Porthaninkatu 9',
  'Helsinki',
  None,
  'Finland',
  '00530',
  8.91),
 (54,
  53,
  '2021-08-16 00:00:00',
  '113 Lupus St',
  'London',
  None,
  'United Kingdom',
  'SW1V 3EN',
  13.86),
 (55,
  8,
  '2021-08-24 00:00:00',
  'Grétrystraat 63',
  'Brussels',
  None,
  'Belgium',
  '1000',
  0.99),
 (56,
  9,
  '2021-09-06 00:00:00',
  'Sønder Boulevard 51',
  'Copenhagen',
  None,
  'Denmark',
  '1720',
  1.98),
 (57,
  11,
  '2021-09-06 00:00:00',
  'Av. Paulista, 2022',
  'São Paulo',
  'SP',
  'Brazil',
  '01310-200',
  1.98),
 (58,
  13,
  '2021-09-07 00:00:00',
  'Qe 7 Bloco G',
  'Brasília',
  'DF',
  'Brazil',
  '71020-677',
  3.96),
 (59,
  17,
  '2021-09-08 00:00:00',
  '1 Microsoft Way',
  'Redmond',
  'WA',
  'USA',
  '98052-8300',
  5.94),
 (60,
  23,
  '2021-09-11 00:00:00',
  '69 Salem Street',
  'Boston',
  'MA',
  'USA',
  '2113',
  8.91),
 (61,
  32,
  '2021-09-16 00:00:00',
  '696 Osborne Street',
  'Winnipeg',
  'MB',
  'Canada',
  'R3L 2B9',
  13.86),
 (62,
  46,
  '2021-09-24 00:00:00',
  '3 Chatham Street',
  'Dublin',
  'Dublin',
  'Ireland',
  None,
  0.99),
 (63,
  47,
  '2021-10-07 00:00:00',
  'Via Degli Scipioni, 43',
  'Rome',
  'RM',
  'Italy',
  '00192',
  1.98),
 (64,
  49,
  '2021-10-07 00:00:00',
  'Ordynacka 10',
  'Warsaw',
  None,
  'Poland',
  '00-358',
  1.98),
 (65,
  51,
  '2021-10-08 00:00:00',
  'Celsiusg. 9',
  'Stockholm',
  None,
  'Sweden',
  '11230',
  3.96),
 (66,
  55,
  '2021-10-09 00:00:00',
  '421 Bourke Street',
  'Sidney',
  'NSW',
  'Australia',
  '2010',
  5.94),
 (67,
  2,
  '2021-10-12 00:00:00',
  'Theodor-Heuss-Straße 34',
  'Stuttgart',
  None,
  'Germany',
  '70174',
  8.91),
 (68,
  11,
  '2021-10-17 00:00:00',
  'Av. Paulista, 2022',
  'São Paulo',
  'SP',
  'Brazil',
  '01310-200',
  13.86),
 (69,
  25,
  '2021-10-25 00:00:00',
  '319 N. Frances Street',
  'Madison',
  'WI',
  'USA',
  '53703',
  0.99),
 (70,
  26,
  '2021-11-07 00:00:00',
  '2211 W Berry Street',
  'Fort Worth',
  'TX',
  'USA',
  '76110',
  1.98),
 (71,
  28,
  '2021-11-07 00:00:00',
  '302 S 700 E',
  'Salt Lake City',
  'UT',
  'USA',
  '84102',
  1.98),
 (72,
  30,
  '2021-11-08 00:00:00',
  '230 Elgin Street',
  'Ottawa',
  'ON',
  'Canada',
  'K2P 1L7',
  3.96),
 (73,
  34,
  '2021-11-09 00:00:00',
  'Rua da Assunção 53',
  'Lisbon',
  None,
  'Portugal',
  None,
  5.94),
 (74,
  40,
  '2021-11-12 00:00:00',
  '8, Rue Hanovre',
  'Paris',
  None,
  'France',
  '75002',
  8.91),
 (75,
  49,
  '2021-11-17 00:00:00',
  'Ordynacka 10',
  'Warsaw',
  None,
  'Poland',
  '00-358',
  13.86),
 (76,
  4,
  '2021-11-25 00:00:00',
  'Ullevålsveien 14',
  'Oslo',
  None,
  'Norway',
  '0171',
  0.99),
 (77,
  5,
  '2021-12-08 00:00:00',
  'Klanova 9/506',
  'Prague',
  None,
  'Czech Republic',
  '14700',
  1.98),
 (78,
  7,
  '2021-12-08 00:00:00',
  'Rotenturmstraße 4, 1010 Innere Stadt',
  'Vienne',
  None,
  'Austria',
  '1010',
  1.98),
 (79,
  9,
  '2021-12-09 00:00:00',
  'Sønder Boulevard 51',
  'Copenhagen',
  None,
  'Denmark',
  '1720',
  3.96),
 (80,
  13,
  '2021-12-10 00:00:00',
  'Qe 7 Bloco G',
  'Brasília',
  'DF',
  'Brazil',
  '71020-677',
  5.94),
 (81,
  19,
  '2021-12-13 00:00:00',
  '1 Infinite Loop',
  'Cupertino',
  'CA',
  'USA',
  '95014',
  8.91),
 (82,
  28,
  '2021-12-18 00:00:00',
  '302 S 700 E',
  'Salt Lake City',
  'UT',
  'USA',
  '84102',
  13.86),
 (83,
  42,
  '2021-12-26 00:00:00',
  '9, Place Louis Barthou',
  'Bordeaux',
  None,
  'France',
  '33000',
  0.99),
 (84,
  43,
  '2022-01-08 00:00:00',
  '68, Rue Jouvence',
  'Dijon',
  None,
  'France',
  '21000',
  1.98),
 (85,
  45,
  '2022-01-08 00:00:00',
  'Erzsébet krt. 58.',
  'Budapest',
  None,
  'Hungary',
  'H-1073',
  1.98),
 (86,
  47,
  '2022-01-09 00:00:00',
  'Via Degli Scipioni, 43',
  'Rome',
  'RM',
  'Italy',
  '00192',
  3.96),
 (87,
  51,
  '2022-01-10 00:00:00',
  'Celsiusg. 9',
  'Stockholm',
  None,
  'Sweden',
  '11230',
  6.94),
 (88,
  57,
  '2022-01-13 00:00:00',
  'Calle Lira, 198',
  'Santiago',
  None,
  'Chile',
  None,
  17.91),
 (89,
  7,
  '2022-01-18 00:00:00',
  'Rotenturmstraße 4, 1010 Innere Stadt',
  'Vienne',
  None,
  'Austria',
  '1010',
  18.86),
 (90,
  21,
  '2022-01-26 00:00:00',
  '801 W 4th Street',
  'Reno',
  'NV',
  'USA',
  '89503',
  0.99),
 (91,
  22,
  '2022-02-08 00:00:00',
  '120 S Orange Ave',
  'Orlando',
  'FL',
  'USA',
  '32801',
  1.98),
 (92,
  24,
  '2022-02-08 00:00:00',
  '162 E Superior Street',
  'Chicago',
  'IL',
  'USA',
  '60611',
  1.98),
 (93,
  26,
  '2022-02-09 00:00:00',
  '2211 W Berry Street',
  'Fort Worth',
  'TX',
  'USA',
  '76110',
  3.96),
 (94,
  30,
  '2022-02-10 00:00:00',
  '230 Elgin Street',
  'Ottawa',
  'ON',
  'Canada',
  'K2P 1L7',
  5.94),
 (95,
  36,
  '2022-02-13 00:00:00',
  'Tauentzienstraße 8',
  'Berlin',
  None,
  'Germany',
  '10789',
  8.91),
 (96,
  45,
  '2022-02-18 00:00:00',
  'Erzsébet krt. 58.',
  'Budapest',
  None,
  'Hungary',
  'H-1073',
  21.86),
 (97,
  59,
  '2022-02-26 00:00:00',
  '3,Raj Bhavan Road',
  'Bangalore',
  None,
  'India',
  '560001',
  1.99),
 (98,
  1,
  '2022-03-11 00:00:00',
  'Av. Brigadeiro Faria Lima, 2170',
  'São José dos Campos',
  'SP',
  'Brazil',
  '12227-000',
  3.98),
 (99,
  3,
  '2022-03-11 00:00:00',
  '1498 rue Bélanger',
  'Montréal',
  'QC',
  'Canada',
  'H2G 1A7',
  3.98),
 (100,
  5,
  '2022-03-12 00:00:00',
  'Klanova 9/506',
  'Prague',
  None,
  'Czech Republic',
  '14700',
  3.96),
 (101,
  9,
  '2022-03-13 00:00:00',
  'Sønder Boulevard 51',
  'Copenhagen',
  None,
  'Denmark',
  '1720',
  5.94),
 (102,
  15,
  '2022-03-16 00:00:00',
  '700 W Pender Street',
  'Vancouver',
  'BC',
  'Canada',
  'V6C 1G8',
  9.91),
 (103,
  24,
  '2022-03-21 00:00:00',
  '162 E Superior Street',
  'Chicago',
  'IL',
  'USA',
  '60611',
  15.86),
 (104,
  38,
  '2022-03-29 00:00:00',
  'Barbarossastraße 19',
  'Berlin',
  None,
  'Germany',
  '10779',
  0.99),
 (105,
  39,
  '2022-04-11 00:00:00',
  '4, Rue Milton',
  'Paris',
  None,
  'France',
  '75009',
  1.98),
 (106,
  41,
  '2022-04-11 00:00:00',
  '11, Place Bellecour',
  'Lyon',
  None,
  'France',
  '69002',
  1.98),
 (107,
  43,
  '2022-04-12 00:00:00',
  '68, Rue Jouvence',
  'Dijon',
  None,
  'France',
  '21000',
  3.96),
 (108,
  47,
  '2022-04-13 00:00:00',
  'Via Degli Scipioni, 43',
  'Rome',
  'RM',
  'Italy',
  '00192',
  5.94),
 (109,
  53,
  '2022-04-16 00:00:00',
  '113 Lupus St',
  'London',
  None,
  'United Kingdom',
  'SW1V 3EN',
  8.91),
 (110,
  3,
  '2022-04-21 00:00:00',
  '1498 rue Bélanger',
  'Montréal',
  'QC',
  'Canada',
  'H2G 1A7',
  13.86),
 (111,
  17,
  '2022-04-29 00:00:00',
  '1 Microsoft Way',
  'Redmond',
  'WA',
  'USA',
  '98052-8300',
  0.99),
 (112,
  18,
  '2022-05-12 00:00:00',
  '627 Broadway',
  'New York',
  'NY',
  'USA',
  '10012-2612',
  1.98),
 (113,
  20,
  '2022-05-12 00:00:00',
  '541 Del Medio Avenue',
  'Mountain View',
  'CA',
  'USA',
  '94040-111',
  1.98),
 (114,
  22,
  '2022-05-13 00:00:00',
  '120 S Orange Ave',
  'Orlando',
  'FL',
  'USA',
  '32801',
  3.96),
 (115,
  26,
  '2022-05-14 00:00:00',
  '2211 W Berry Street',
  'Fort Worth',
  'TX',
  'USA',
  '76110',
  5.94),
 (116,
  32,
  '2022-05-17 00:00:00',
  '696 Osborne Street',
  'Winnipeg',
  'MB',
  'Canada',
  'R3L 2B9',
  8.91),
 (117,
  41,
  '2022-05-22 00:00:00',
  '11, Place Bellecour',
  'Lyon',
  None,
  'France',
  '69002',
  13.86),
 (118,
  55,
  '2022-05-30 00:00:00',
  '421 Bourke Street',
  'Sidney',
  'NSW',
  'Australia',
  '2010',
  0.99),
 (119,
  56,
  '2022-06-12 00:00:00',
  '307 Macacha Güemes',
  'Buenos Aires',
  None,
  'Argentina',
  '1106',
  1.98),
 (120,
  58,
  '2022-06-12 00:00:00',
  '12,Community Centre',
  'Delhi',
  None,
  'India',
  '110017',
  1.98),
 (121,
  1,
  '2022-06-13 00:00:00',
  'Av. Brigadeiro Faria Lima, 2170',
  'São José dos Campos',
  'SP',
  'Brazil',
  '12227-000',
  3.96),
 (122,
  5,
  '2022-06-14 00:00:00',
  'Klanova 9/506',
  'Prague',
  None,
  'Czech Republic',
  '14700',
  5.94),
 (123,
  11,
  '2022-06-17 00:00:00',
  'Av. Paulista, 2022',
  'São Paulo',
  'SP',
  'Brazil',
  '01310-200',
  8.91),
 (124,
  20,
  '2022-06-22 00:00:00',
  '541 Del Medio Avenue',
  'Mountain View',
  'CA',
  'USA',
  '94040-111',
  13.86),
 (125,
  34,
  '2022-06-30 00:00:00',
  'Rua da Assunção 53',
  'Lisbon',
  None,
  'Portugal',
  None,
  0.99),
 (126,
  35,
  '2022-07-13 00:00:00',
  'Rua dos Campeões Europeus de Viena, 4350',
  'Porto',
  None,
  'Portugal',
  None,
  1.98),
 (127,
  37,
  '2022-07-13 00:00:00',
  'Berger Straße 10',
  'Frankfurt',
  None,
  'Germany',
  '60316',
  1.98),
 (128,
  39,
  '2022-07-14 00:00:00',
  '4, Rue Milton',
  'Paris',
  None,
  'France',
  '75009',
  3.96),
 (129,
  43,
  '2022-07-15 00:00:00',
  '68, Rue Jouvence',
  'Dijon',
  None,
  'France',
  '21000',
  5.94),
 (130,
  49,
  '2022-07-18 00:00:00',
  'Ordynacka 10',
  'Warsaw',
  None,
  'Poland',
  '00-358',
  8.91),
 (131,
  58,
  '2022-07-23 00:00:00',
  '12,Community Centre',
  'Delhi',
  None,
  'India',
  '110017',
  13.86),
 (132,
  13,
  '2022-07-31 00:00:00',
  'Qe 7 Bloco G',
  'Brasília',
  'DF',
  'Brazil',
  '71020-677',
  0.99),
 (133,
  14,
  '2022-08-13 00:00:00',
  '8210 111 ST NW',
  'Edmonton',
  'AB',
  'Canada',
  'T6G 2C7',
  1.98),
 (134,
  16,
  '2022-08-13 00:00:00',
  '1600 Amphitheatre Parkway',
  'Mountain View',
  'CA',
  'USA',
  '94043-1351',
  1.98),
 (135,
  18,
  '2022-08-14 00:00:00',
  '627 Broadway',
  'New York',
  'NY',
  'USA',
  '10012-2612',
  3.96),
 (136,
  22,
  '2022-08-15 00:00:00',
  '120 S Orange Ave',
  'Orlando',
  'FL',
  'USA',
  '32801',
  5.94),
 (137,
  28,
  '2022-08-18 00:00:00',
  '302 S 700 E',
  'Salt Lake City',
  'UT',
  'USA',
  '84102',
  8.91),
 (138,
  37,
  '2022-08-23 00:00:00',
  'Berger Straße 10',
  'Frankfurt',
  None,
  'Germany',
  '60316',
  13.86),
 (139,
  51,
  '2022-08-31 00:00:00',
  'Celsiusg. 9',
  'Stockholm',
  None,
  'Sweden',
  '11230',
  0.99),
 (140,
  52,
  '2022-09-13 00:00:00',
  '202 Hoxton Street',
  'London',
  None,
  'United Kingdom',
  'N1 5LH',
  1.98),
 (141,
  54,
  '2022-09-13 00:00:00',
  '110 Raeburn Pl',
  'Edinburgh ',
  None,
  'United Kingdom',
  'EH4 1HH',
  1.98),
 (142,
  56,
  '2022-09-14 00:00:00',
  '307 Macacha Güemes',
  'Buenos Aires',
  None,
  'Argentina',
  '1106',
  3.96),
 (143,
  1,
  '2022-09-15 00:00:00',
  'Av. Brigadeiro Faria Lima, 2170',
  'São José dos Campos',
  'SP',
  'Brazil',
  '12227-000',
  5.94),
 (144,
  7,
  '2022-09-18 00:00:00',
  'Rotenturmstraße 4, 1010 Innere Stadt',
  'Vienne',
  None,
  'Austria',
  '1010',
  8.91),
 (145,
  16,
  '2022-09-23 00:00:00',
  '1600 Amphitheatre Parkway',
  'Mountain View',
  'CA',
  'USA',
  '94043-1351',
  13.86),
 (146,
  30,
  '2022-10-01 00:00:00',
  '230 Elgin Street',
  'Ottawa',
  'ON',
  'Canada',
  'K2P 1L7',
  0.99),
 (147,
  31,
  '2022-10-14 00:00:00',
  '194A Chain Lake Drive',
  'Halifax',
  'NS',
  'Canada',
  'B3S 1C5',
  1.98),
 (148,
  33,
  '2022-10-14 00:00:00',
  '5112 48 Street',
  'Yellowknife',
  'NT',
  'Canada',
  'X1A 1N6',
  1.98),
 (149,
  35,
  '2022-10-15 00:00:00',
  'Rua dos Campeões Europeus de Viena, 4350',
  'Porto',
  None,
  'Portugal',
  None,
  3.96),
 (150,
  39,
  '2022-10-16 00:00:00',
  '4, Rue Milton',
  'Paris',
  None,
  'France',
  '75009',
  5.94),
 (151,
  45,
  '2022-10-19 00:00:00',
  'Erzsébet krt. 58.',
  'Budapest',
  None,
  'Hungary',
  'H-1073',
  8.91),
 (152,
  54,
  '2022-10-24 00:00:00',
  '110 Raeburn Pl',
  'Edinburgh ',
  None,
  'United Kingdom',
  'EH4 1HH',
  13.86),
 (153,
  9,
  '2022-11-01 00:00:00',
  'Sønder Boulevard 51',
  'Copenhagen',
  None,
  'Denmark',
  '1720',
  0.99),
 (154,
  10,
  '2022-11-14 00:00:00',
  'Rua Dr. Falcão Filho, 155',
  'São Paulo',
  'SP',
  'Brazil',
  '01007-010',
  1.98),
 (155,
  12,
  '2022-11-14 00:00:00',
  'Praça Pio X, 119',
  'Rio de Janeiro',
  'RJ',
  'Brazil',
  '20040-020',
  1.98),
 (156,
  14,
  '2022-11-15 00:00:00',
  '8210 111 ST NW',
  'Edmonton',
  'AB',
  'Canada',
  'T6G 2C7',
  3.96),
 (157,
  18,
  '2022-11-16 00:00:00',
  '627 Broadway',
  'New York',
  'NY',
  'USA',
  '10012-2612',
  5.94),
 (158,
  24,
  '2022-11-19 00:00:00',
  '162 E Superior Street',
  'Chicago',
  'IL',
  'USA',
  '60611',
  8.91),
 (159,
  33,
  '2022-11-24 00:00:00',
  '5112 48 Street',
  'Yellowknife',
  'NT',
  'Canada',
  'X1A 1N6',
  13.86),
 (160,
  47,
  '2022-12-02 00:00:00',
  'Via Degli Scipioni, 43',
  'Rome',
  'RM',
  'Italy',
  '00192',
  0.99),
 (161,
  48,
  '2022-12-15 00:00:00',
  'Lijnbaansgracht 120bg',
  'Amsterdam',
  'VV',
  'Netherlands',
  '1016',
  1.98),
 (162,
  50,
  '2022-12-15 00:00:00',
  'C/ San Bernardo 85',
  'Madrid',
  None,
  'Spain',
  '28015',
  1.98),
 (163,
  52,
  '2022-12-16 00:00:00',
  '202 Hoxton Street',
  'London',
  None,
  'United Kingdom',
  'N1 5LH',
  3.96),
 (164,
  56,
  '2022-12-17 00:00:00',
  '307 Macacha Güemes',
  'Buenos Aires',
  None,
  'Argentina',
  '1106',
  5.94),
 (165,
  3,
  '2022-12-20 00:00:00',
  '1498 rue Bélanger',
  'Montréal',
  'QC',
  'Canada',
  'H2G 1A7',
  8.91),
 (166,
  12,
  '2022-12-25 00:00:00',
  'Praça Pio X, 119',
  'Rio de Janeiro',
  'RJ',
  'Brazil',
  '20040-020',
  13.86),
 (167,
  26,
  '2023-01-02 00:00:00',
  '2211 W Berry Street',
  'Fort Worth',
  'TX',
  'USA',
  '76110',
  0.99),
 (168,
  27,
  '2023-01-15 00:00:00',
  '1033 N Park Ave',
  'Tucson',
  'AZ',
  'USA',
  '85719',
  1.98),
 (169,
  29,
  '2023-01-15 00:00:00',
  '796 Dundas Street West',
  'Toronto',
  'ON',
  'Canada',
  'M6J 1V1',
  1.98),
 (170,
  31,
  '2023-01-16 00:00:00',
  '194A Chain Lake Drive',
  'Halifax',
  'NS',
  'Canada',
  'B3S 1C5',
  3.96),
 (171,
  35,
  '2023-01-17 00:00:00',
  'Rua dos Campeões Europeus de Viena, 4350',
  'Porto',
  None,
  'Portugal',
  None,
  5.94),
 (172,
  41,
  '2023-01-20 00:00:00',
  '11, Place Bellecour',
  'Lyon',
  None,
  'France',
  '69002',
  8.91),
 (173,
  50,

In [6]:
tracks_df = pd.read_sql_query("SELECT * FROM Customer", db)
tracks_df.sample(10)

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
34,35,Madalena,Sampaio,NaN,"Rua dos Campeões Europeus de Viena, 4350",Porto,NaN,Portugal,NaN,+351 (225) 022-448,NaN,masampaio@sapo.pt,4
9,10,Eduardo,Martins,Woodstock Discos,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,+55 (11) 3033-5446,+55 (11) 3033-4564,eduardo@woodstock.com.br,4
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
45,46,Hugh,O'Reilly,NaN,3 Chatham Street,Dublin,Dublin,Ireland,NaN,+353 01 6792424,NaN,hughoreilly@apple.ie,3
12,13,Fernanda,Ramos,NaN,Qe 7 Bloco G,Brasília,DF,Brazil,71020-677,+55 (61) 3363-5547,+55 (61) 3363-7855,fernadaramos4@uol.com.br,4
38,39,Camille,Bernard,NaN,"4, Rue Milton",Paris,NaN,France,75009,+33 01 49 70 65 65,NaN,camille.bernard@yahoo.fr,4
17,18,Michelle,Brooks,NaN,627 Broadway,New York,NY,USA,10012-2612,+1 (212) 221-3546,+1 (212) 221-4679,michelleb@aol.com,3
1,2,Leonie,Köhler,NaN,Theodor-Heuss-Straße 34,Stuttgart,NaN,Germany,70174,+49 0711 2842222,NaN,leonekohler@surfeu.de,5
11,12,Roberto,Almeida,Riotur,"Praça Pio X, 119",Rio de Janeiro,RJ,Brazil,20040-020,+55 (21) 2271-7000,+55 (21) 2271-7070,roberto.almeida@riotur.gov.br,3
35,36,Hannah,Schneider,NaN,Tauentzienstraße 8,Berlin,NaN,Germany,10789,+49 030 26550280,NaN,hannah.schneider@yahoo.de,5

In [7]:
album_df = pd.read_sql_query("SELECT * FROM Artist", db)
album_df

     ArtistId                                               Name
0           1                                              AC/DC
1           2                                             Accept
2           3                                          Aerosmith
3           4                                  Alanis Morissette
4           5                                    Alice In Chains
..        ...                                                ...
270       271   Mela Tenenbaum, Pro Musica Prague & Richard Kapp
271       272                             Emerson String Quartet
272       273  C. Monteverdi, Nigel Rogers - Chiaroscuro; Lon...
273       274                                      Nash Ensemble
274       275                              Philip Glass Ensemble

[275 rows x 2 columns]

In [9]:
#album_df[album_df.AlbumId == 223]

In [10]:
artist_df = pd.read_sql_query("SELECT * FROM Artist", db)
artist_df.sample(10)

     ArtistId           Name
23         24   Marcos Valle
51         52           Kiss
80         81   Eric Clapton
269       270   Gerald Moore
181       182     Nega Gizza
169       170   Jack Johnson
83         84   Foo Fighters
151       152      Van Halen
179       180  House Of Pain
198       199     Karsh Kale

In [11]:
#practice
_q = """
    SELECT 
        Name
    FROM 
        Artist
        WHERE ArtistId = 81
        """
pd.read_sql_query(_q, db)

           Name
0  Eric Clapton

In [12]:
artist_df[artist_df.ArtistId == 145]

     ArtistId      Name
144       145  Tim Maia

In [13]:
tracks_df.shape, album_df.shape

((59, 13), (275, 2))

In [14]:
# tracks_df = pd.read_sql_query("SELECT TrackId, Name, AlbumId FROM Track", db)
# tracks_df.sample(10)

_q = """
SELECT 
    TrackId, 
    Name, 
    AlbumId
FROM Track 
LIMIT 5
"""

pd.read_sql_query(_q, db)

   TrackId                                     Name  AlbumId
0        1  For Those About To Rock (We Salute You)        1
1        2                        Balls to the Wall        2
2        3                          Fast As a Shark        3
3        4                        Restless and Wild        3
4        5                     Princess of the Dawn        3

In [15]:
_q = """
SELECT 
    *
FROM Album 
LIMIT 5
"""

pd.read_sql_query(_q, db)

   AlbumId                                  Title  ArtistId
0        1  For Those About To Rock We Salute You         1
1        2                      Balls to the Wall         2
2        3                      Restless and Wild         2
3        4                      Let There Be Rock         1
4        5                               Big Ones         3

In [16]:
_q = """
SELECT 
    t.TrackId, 
    t.Name, 
    t.AlbumId,
    a.*
FROM Track as t
JOIN Album as a
ON t.AlbumId = a.AlbumId 
"""
pd.read_sql_query(_q, db)

,TrackId,Name,AlbumId,AlbumId,Title,ArtistId
0,1,For Those About To Rock (We Salute You),1,1,For Those About To Rock We Salute You,1
1,2,Balls to the Wall,2,2,Balls to the Wall,2
2,3,Fast As a Shark,3,3,Restless and Wild,2
3,4,Restless and Wild,3,3,Restless and Wild,2
4,5,Princess of the Dawn,3,3,Restless and Wild,2
...,...,...,...,...,...,...
3498,3499,Pini Di Roma (Pinien Von Rom) \ I Pini Della V...,343,343,Respighi:Pines of Rome,226
3499,3500,"String Quartet No. 12 in C Minor, D. 703 ""Quar...",344,344,Schubert: The Late String Quartets & String Qu...,272
3500,3501,"L'orfeo, Act 3, Sinfonia (Orchestra)",345,345,Monteverdi: L'Orfeo,273
3501,3502,"Quintet for Horn, Violin, 2 Violas, and Cello ...",346,346,Mozart: Chamber Music,274
3502,3503,Koyaanisqatsi,347,347,Koyaanisqatsi (Soundtrack from the Motion Pict...,275

In [17]:
_q = """
SELECT 
    t.TrackId, 
    t.Name as track_name, 
    t.UnitPrice,
    a.AlbumId,
    a.Title as album_title,
    ar.ArtistId,
    ar.Name as artist_name

FROM Track as t
JOIN Album as a
ON t.AlbumId = a.AlbumId 
JOIN Artist as ar
ON a.ArtistId = ar.ArtistId

WHERE t.UnitPrice > 1
"""
pd.read_sql_query(_q, db)

,TrackId,track_name,UnitPrice,AlbumId,album_title,ArtistId,artist_name
0,2819,Battlestar Galactica: The Story So Far,1.99,226,Battlestar Galactica: The Story So Far,147,Battlestar Galactica
1,2820,Occupation / Precipice,1.99,227,"Battlestar Galactica, Season 3",147,Battlestar Galactica
2,2821,"Exodus, Pt. 1",1.99,227,"Battlestar Galactica, Season 3",147,Battlestar Galactica
3,2822,"Exodus, Pt. 2",1.99,227,"Battlestar Galactica, Season 3",147,Battlestar Galactica
4,2823,Collaborators,1.99,227,"Battlestar Galactica, Season 3",147,Battlestar Galactica
...,...,...,...,...,...,...,...
208,3362,"There's No Place Like Home, Pt. 1",1.99,261,"LOST, Season 4",149,Lost
209,3363,"There's No Place Like Home, Pt. 2",1.99,261,"LOST, Season 4",149,Lost
210,3364,"There's No Place Like Home, Pt. 3",1.99,261,"LOST, Season 4",149,Lost
211,3428,Branch Closing,1.99,251,"The Office, Season 3",156,The Office
212,3429,The Return,1.99,251,"The Office, Season 3",156,The Office

SQL - Declarative Lang
Python - Imperative Lang

1. CTE

In [18]:
_q = """
WITH newTable AS (
    SELECT 
        t.TrackId, 
        t.Name as track_name, 
        t.UnitPrice,
        a.AlbumId,
        a.Title as album_title
    FROM Track as t
    JOIN Album as a
        ON t.AlbumId = a.AlbumId 
    WHERE t.UnitPrice > 1
)


SELECT 
    album_title, 
    SUM(UnitPrice) as total_price 
FROM newTable
GROUP BY album_title
ORDER BY total_price DESC
"""
pd.read_sql_query(_q, db)

                                 album_title  total_price
0                             Lost, Season 3        51.74
1                       The Office, Season 3        49.75
2                             Lost, Season 1        49.75
3                             Lost, Season 2        47.76
4   Battlestar Galactica (Classic), Season 1        47.76
5                           Heroes, Season 1        45.77
6                       The Office, Season 2        43.78
7             Battlestar Galactica, Season 3        37.81
8                             LOST, Season 4        33.83
9                       The Office, Season 1        11.94
10    Battlestar Galactica: The Story So Far         1.99
11                                   Aquaman         1.99

# Questions

1. Number of Tracks are longer than 1 Million Millisecond 
2. For Each Genre, how many tracks are there
3. Which Artist has the highest number of tracks and how many do they have
4. Which Track sold the most and how many copies, what the total revenue from sale of that track (sql+pandas)
5. which Album in total is the biggest in Size ( Track - Bytes)
6. Explore MediaType 
7. Number of employees and Number of customers
8. which customer got the most number of tracks, what tracks did they get.

In [19]:
_q=""" SELECT * FROM Track"""

pd.read_sql_query(_q, db)

,TrackId,Name,AlbumId,MediaTypeId,GenreId,Composer,Milliseconds,Bytes,UnitPrice
0,1,For Those About To Rock (We Salute You),1,1,1,"Angus Young, Malcolm Young, Brian Johnson",343719,11170334,0.99
1,2,Balls to the Wall,2,2,1,"U. Dirkschneider, W. Hoffmann, H. Frank, P. Ba...",342562,5510424,0.99
2,3,Fast As a Shark,3,2,1,"F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho...",230619,3990994,0.99
3,4,Restless and Wild,3,2,1,"F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D...",252051,4331779,0.99
4,5,Princess of the Dawn,3,2,1,Deaffy & R.A. Smith-Diesel,375418,6290521,0.99
...,...,...,...,...,...,...,...,...,...
3498,3499,Pini Di Roma (Pinien Von Rom) \ I Pini Della V...,343,2,24,NaN,286741,4718950,0.99
3499,3500,"String Quartet No. 12 in C Minor, D. 703 ""Quar...",344,2,24,Franz Schubert,139200,2283131,0.99
3500,3501,"L'orfeo, Act 3, Sinfonia (Orchestra)",345,2,24,Claudio Monteverdi,66639,1189062,0.99
3501,3502,"Quintet for Horn, Violin, 2 Violas, and Cello ...",346,2,24,Wolfgang Amadeus Mozart,221331,3665114,0.99
3502,3503,Koyaanisqatsi,347,2,10,Philip Glass,206005,3305164,0.99

In [20]:
#1. Number of Tracks are longer than 1 Million Millisecond, answer is 214
_q=""" SELECT Name,Milliseconds FROM Track
WHERE milliseconds >1000000"""
pd.read_sql_query(_q, db)

                                       Name  Milliseconds
0                            Space Truckin'       1196094
1                        Dazed And Confused       1116734
2                        Dazed And Confused       1612329
3           We've Got To Get Together/Jingo       1070027
4    Battlestar Galactica: The Story So Far       2622250
..                                      ...           ...
210       There's No Place Like Home, Pt. 1       2609526
211       There's No Place Like Home, Pt. 2       2497956
212       There's No Place Like Home, Pt. 3       2582957
213                          Branch Closing       1814855
214                              The Return       1705080

[215 rows x 2 columns]

In [21]:
#2. For Each Genre, how many tracks are there?
#COUNT(*) IS A function that counts the number of rows in a group. It is often used in conjunction with the GROUP BY clause to count the number of occurrences of each unique value in a column.
_q=""" SELECT GenreID, COUNT(*) as num_tracks 
FROM Track
GROUP BY GenreID
ORDER BY num_tracks DESC
"""
pd.read_sql_query(_q, db)

    GenreId  num_tracks
0         1        1297
1         7         579
2         3         374
3         4         332
4         2         130
5        19          93
6         6          81
7        24          74
8        21          64
9        14          61
10        8          58
11        9          48
12       10          43
13       23          40
14       17          35
15       15          30
16       13          28
17       16          28
18       20          26
19       12          24
20       22          17
21       11          15
22       18          13
23        5          12
24       25           1

In [22]:
# 3.Which Artist has the highest number of tracks and how many do they have
_q="""
SELECT ArtistId,COUNT(*) as num_tracks
FROM Track as t
JOIN Album as a
ON t.AlbumId = a.AlbumId
GROUP BY ArtistId
ORDER BY num_tracks DESC"""
pd.read_sql_query(_q, db)

     ArtistId  num_tracks
0          90         213
1         150         135
2          22         114
3          50         112
4          58          92
..        ...         ...
199       271           1
200       272           1
201       273           1
202       274           1
203       275           1

[204 rows x 2 columns]

In [ ]:
#Which Track sold the most and how many copies, what the total revenue from sale of that track (sql+pandas)

SyntaxError: invalid syntax (1555038936.py, line 1)

In [24]:
print(tables)

[('Album',), ('Artist',), ('Customer',), ('Employee',), ('Genre',), ('Invoice',), ('InvoiceLine',), ('MediaType',), ('Playlist',), ('PlaylistTrack',), ('Track',)]

In [30]:
#4. Which Track sold the most and how many copies, what the total revenue from sale of that track (sql+pandas)

_q="""
SELECT
    i.InvoiceId,
    i.CustomerId,
    i.Total,
    il.TrackId,
    il.UnitPrice,
    il.Quantity
FROM Invoice as i
JOIN InvoiceLine as il
ON i.InvoiceId = il.InvoiceId
"""
sales_df = pd.read_sql_query(_q, db)
sales_df.groupby("TrackId")["InvoiceId"].sum().sort_values(ascending=False)

TrackId
3177    718
2945    704
2713    690
2481    676
2249    662
       ...
16        3
10        2
6         2
12        2
4         1
Name: InvoiceId, Length: 1984, dtype: int64

In [ ]:
#5. which Album in total is the biggest in Size ( Track - Bytes)
_q="""
SELECT AlbumId,Bytes
FROM Track
ORDER BY Bytes DESC"""
pd.read_sql_query(_q, db)

      AlbumId       Bytes
0         229  1059546140
1         227  1054423946
2         253   587051735
3         253   577829804
4         231   574325829
...       ...         ...
3498      258      319888
3499       18      224313
3500       18      211997
3501       18      161266
3502      200       38747

[3503 rows x 2 columns]

In [ ]:
#7. Number of employees
_q="""SELECT COUNT(*) FROM Employee"""
pd.read_sql_query(_q, db)

   COUNT(*)
0         8

In [ ]:
#8. Number of customers
_q="""SELECT COUNT(*)  FROM Customer"""
pd.read_sql_query(_q, db)

   COUNT(*)
0        59

In [ ]:
#8. which customer got the most number of tracks, what tracks did they get. 
_q="""
SELECT c.CustomerId,AlbumId,Name, il.TrackId, c.FirstName, c.LastName, COUNT(t.TrackId) AS TrackCount
FROM Customer as c
JOIN Invoice as i
ON c.CustomerId=i.CustomerId
JOIN InvoiceLine as il
ON i.InvoiceId=il.InvoiceId
JOIN Track as t
ON il.TrackId=t.TrackId
GROUP BY c.CustomerId
ORDER BY TrackCount DESC
LIMIT 1
"""
pd.read_sql_query(_q, db)

   CustomerId  AlbumId      Name  TrackId FirstName LastName  TrackCount
0          58       37  Shock Me      443     Manoj   Pareek          38

In [ ]:
#8. Number of customers
_q="""SELECT Name FROM Track
WHERE TrackId = 443"""
pd.read_sql_query(_q, db)

       Name
0  Shock Me